### ISSUE TITLE
Avoid generating text files

### ISSUE THREAD

**Issue by yocra3** [isglobal-brge/EASIER#1]
Enrichment functions such as `missMethyl_enrichment` write the results to a file and return them as an object. Although this can be the default behaviour, it should be possible to not write any file to disk and only return an object, like for `get_consensusPdb_OverRepresentation` function.

**Comment by isglobal-brge** [comment]
I completely agree ... This is a very Mariona's style - the function could return an object and then the object could be saved as a file ... but we can do both

**Comment by dpelegri** [comment]
Now the script is configured to generate the result in file but disable output files it's easy, you only need to remove the `outputfile` and `outputdir` parameters. The outputfiles are generated only if we set this parameters. 
Perhaps it would be better to add a generic configuration parameter in the script, something like `outputInFiles`, and if `outputInFiles = false` then do not generate results in files.
